CREATE TEMP TABLE a2_checks(check_name text,expected text,actual text,passed boolean,details text);
CREATE TEMP TABLE a2_account AS SELECT id FROM accounts WHERE lower(email)='scale@lifelab.local';

INSERT INTO a2_checks SELECT 'account_count','1',count(*)::text,count(*)=1,'locked A2 identity' FROM a2_account;
INSERT INTO a2_checks SELECT 'library_count','80',count(*)::text,count(*)=80,'final current Library rows' FROM library_videos l JOIN a2_account a ON a.id=l.account_id;
INSERT INTO a2_checks
SELECT 'current_source_set','80 exact',count(*) FILTER(WHERE present)::text||' present / '||count(*) FILTER(WHERE NOT present)||' missing',bool_and(present),'exact current membership'
FROM (SELECT e.fixture_key,EXISTS(SELECT 1 FROM library_videos l JOIN a2_account a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id WHERE y.youtube_video_id=e.youtube_video_id) present FROM a2_expected_sources e WHERE role='CURRENT_LIBRARY') x;
INSERT INTO a2_checks
SELECT 'historical_library_absent','0',count(*)::text,count(*)=0,'20 historical IDs must not have A2 Library rows'
FROM library_videos l JOIN a2_account a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id JOIN a2_expected_sources e USING(youtube_video_id) WHERE e.role='HISTORICAL';
INSERT INTO a2_checks SELECT 'global_sources','100',count(*)::text,count(*)=100,'all locked IDs exist globally' FROM youtube_videos y JOIN a2_expected_sources e USING(youtube_video_id);
INSERT INTO a2_checks SELECT 'library_duplicates','0',count(*)::text,count(*)=0,'unique account/source' FROM (SELECT youtube_source_id FROM library_videos l JOIN a2_account a ON a.id=l.account_id GROUP BY youtube_source_id HAVING count(*)>1)x;
INSERT INTO a2_checks SELECT 'source_compatibility','0',count(*)::text,count(*)=0,'AVAILABLE and <=1 second only for explicit shared sources' FROM youtube_videos y JOIN a2_expected_sources e USING(youtube_video_id) WHERE y.availability_status<>'AVAILABLE' OR (e.shared AND abs(y.duration_seconds-e.duration_seconds)>1) OR (NOT e.shared AND y.duration_seconds<>e.duration_seconds);
INSERT INTO a2_checks SELECT 'source_time_invariants','0',count(*)::text,count(*)=0,'non-shared source created/published/updated/reference ordering' FROM youtube_videos y JOIN a2_expected_sources e USING(youtube_video_id) WHERE NOT e.shared AND (y.created_at<y.published_at OR y.created_at>y.updated_at OR y.created_at>((:'reference_date'::date::timestamp+time '12:00') AT TIME ZONE 'Asia/Ho_Chi_Minh'));

INSERT INTO a2_checks SELECT 'tag_count','25',count(*)::text,count(*)=25,'A2 Tags' FROM tags t JOIN a2_account a ON a.id=t.account_id;
INSERT INTO a2_checks SELECT 'tag_normalization','0',count(*)::text,count(*)=0,'normalized unique collapsed lowercase names' FROM tags t JOIN a2_account a ON a.id=t.account_id WHERE normalized_name<>lower(regexp_replace(btrim(name),'\s+',' ','g'));
INSERT INTO a2_checks SELECT 'tag_links','200',count(*)::text,count(*)=200,'exact final current links' FROM library_video_tags x JOIN library_videos l ON l.id=x.library_video_id JOIN a2_account a ON a.id=l.account_id;
INSERT INTO a2_checks SELECT 'all_tags_used','25',count(DISTINCT x.tag_id)::text,count(DISTINCT x.tag_id)=25,'every A2 Tag used' FROM library_video_tags x JOIN tags t ON t.id=x.tag_id JOIN a2_account a ON a.id=t.account_id;
INSERT INTO a2_checks SELECT 'tag_link_distribution','0',count(*)::text,count(*)=0,'exact TSV relationships' FROM ((SELECT e.fixture_key,lower(e.tag_name) tag_name FROM a2_expected_links e EXCEPT SELECT s.fixture_key,lower(t.name) FROM library_video_tags x JOIN library_videos l ON l.id=x.library_video_id JOIN a2_account a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id JOIN a2_expected_sources s USING(youtube_video_id) JOIN tags t ON t.id=x.tag_id) UNION ALL (SELECT s.fixture_key,lower(t.name) FROM library_video_tags x JOIN library_videos l ON l.id=x.library_video_id JOIN a2_account a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id JOIN a2_expected_sources s USING(youtube_video_id) JOIN tags t ON t.id=x.tag_id EXCEPT SELECT e.fixture_key,lower(e.tag_name) FROM a2_expected_links e))d;

INSERT INTO a2_checks SELECT 'watch_total','1000',count(*)::text,count(*)=1000,'closed current sessions' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a2_account a ON a.id=l.account_id;
INSERT INTO a2_checks SELECT 'watch_valid','780',count(*)::text,count(*)=780,'VALID only' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a2_account a ON a.id=l.account_id WHERE validity_status='VALID';
INSERT INTO a2_checks SELECT 'watch_invalid','220',count(*)::text,count(*)=220,'INVALID only' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a2_account a ON a.id=l.account_id WHERE validity_status='INVALID';
INSERT INTO a2_checks SELECT 'watch_other_states','0',count(*)::text,count(*)=0,'no PENDING/UNDETERMINED' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a2_account a ON a.id=l.account_id WHERE validity_status NOT IN('VALID','INVALID');
INSERT INTO a2_checks SELECT 'watched_current','64/16',count(*) FILTER(WHERE valid_count>0)::text||'/'||count(*) FILTER(WHERE valid_count=0),count(*) FILTER(WHERE valid_count>0)=64 AND count(*) FILTER(WHERE valid_count=0)=16,'derived watched/unwatched' FROM (SELECT l.id,count(w.id) FILTER(WHERE w.validity_status='VALID') valid_count FROM library_videos l JOIN a2_account a ON a.id=l.account_id LEFT JOIN watch_sessions w ON w.library_video_id=l.id GROUP BY l.id)x;
INSERT INTO a2_checks SELECT 'watch_distribution','0',count(*)::text,count(*)=0,'per-source VALID/INVALID TSV' FROM (SELECT e.fixture_key,e.valid_count,e.invalid_count,count(w.id) FILTER(WHERE w.validity_status='VALID') av,count(w.id) FILTER(WHERE w.validity_status='INVALID') ai FROM a2_expected_watch e JOIN a2_expected_sources s USING(fixture_key) JOIN youtube_videos y USING(youtube_video_id) JOIN library_videos l ON l.youtube_source_id=y.id JOIN a2_account a ON a.id=l.account_id LEFT JOIN watch_sessions w ON w.library_video_id=l.id GROUP BY e.fixture_key,e.valid_count,e.invalid_count HAVING count(w.id) FILTER(WHERE w.validity_status='VALID')<>e.valid_count OR count(w.id) FILTER(WHERE w.validity_status='INVALID')<>e.invalid_count)x;
INSERT INTO a2_checks SELECT 'watch_invariants','0',count(*)::text,count(*)=0,'closed, ordered, threshold-valid and plausible' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a2_account a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id WHERE w.ended_at IS NULL OR w.started_at>w.last_heartbeat_at OR w.last_heartbeat_at>w.ended_at OR w.started_at<l.added_at OR (w.validity_status='VALID' AND w.watch_time_seconds<30) OR (w.validity_status='INVALID' AND w.watch_time_seconds>=30) OR w.watch_time_seconds>y.duration_seconds OR w.watch_time_seconds>extract(epoch FROM(w.ended_at-w.started_at));

INSERT INTO a2_checks SELECT 'note_total','240',count(*)::text,count(*)=240,'final Notes only' FROM notes n JOIN a2_account a ON a.id=n.account_id;
INSERT INTO a2_checks SELECT 'note_role_counts','200/40',count(*) FILTER(WHERE e.role='CURRENT_LIBRARY')::text||'/'||count(*) FILTER(WHERE e.role='HISTORICAL'),count(*) FILTER(WHERE e.role='CURRENT_LIBRARY')=200 AND count(*) FILTER(WHERE e.role='HISTORICAL')=40,'current/historical Notes' FROM notes n JOIN a2_account a ON a.id=n.account_id JOIN youtube_videos y ON y.id=n.youtube_source_id JOIN a2_expected_sources e USING(youtube_video_id);
INSERT INTO a2_checks SELECT 'note_timestamp_counts','120/120',count(*) FILTER(WHERE timestamp_seconds IS NOT NULL)::text||'/'||count(*) FILTER(WHERE timestamp_seconds IS NULL),count(*) FILTER(WHERE timestamp_seconds IS NOT NULL)=120 AND count(*) FILTER(WHERE timestamp_seconds IS NULL)=120,'timestamped/NULL' FROM notes n JOIN a2_account a ON a.id=n.account_id;
INSERT INTO a2_checks SELECT 'note_fixture_distribution','0',count(*)::text,count(*)=0,'content-independent per-source/timestamp multiset' FROM ((SELECT e.youtube_video_id,e.timestamp_seconds,count(*) FROM a2_expected_notes e GROUP BY e.youtube_video_id,e.timestamp_seconds EXCEPT SELECT y.youtube_video_id,n.timestamp_seconds,count(*) FROM notes n JOIN a2_account a ON a.id=n.account_id JOIN youtube_videos y ON y.id=n.youtube_source_id GROUP BY y.youtube_video_id,n.timestamp_seconds) UNION ALL (SELECT y.youtube_video_id,n.timestamp_seconds,count(*) FROM notes n JOIN a2_account a ON a.id=n.account_id JOIN youtube_videos y ON y.id=n.youtube_source_id GROUP BY y.youtube_video_id,n.timestamp_seconds EXCEPT SELECT e.youtube_video_id,e.timestamp_seconds,count(*) FROM a2_expected_notes e GROUP BY e.youtube_video_id,e.timestamp_seconds))d;
INSERT INTO a2_checks SELECT 'note_vtt_evidence','0',count(*)::text,count(*)=0,'exact source cue evidence and effective DB duration bounds' FROM a2_expected_notes e JOIN a2_expected_sources s USING(fixture_key) JOIN youtube_videos y ON y.youtube_video_id=e.youtube_video_id WHERE e.timestamp_seconds IS NOT NULL AND (e.vtt_track IS NULL OR e.timestamp_seconds IS DISTINCT FROM e.cue_start_seconds OR e.timestamp_seconds<0 OR e.timestamp_seconds>=s.duration_seconds OR e.timestamp_seconds>=y.duration_seconds);
INSERT INTO a2_checks SELECT 'no_vtt_timestamp','0',count(*)::text,count(*)=0,'six no-VTT sources have no timestamped fixture' FROM a2_expected_notes n JOIN a2_expected_sources s USING(fixture_key) WHERE NOT s.has_vtt AND n.timestamp_seconds IS NOT NULL;

INSERT INTO a2_checks SELECT 'task_total','400',count(*)::text,count(*)=400,'all A2 Tasks' FROM tasks t JOIN a2_account a ON a.id=t.account_id;
INSERT INTO a2_checks SELECT 'task_source_matrix','170/190/40',count(*) FILTER(WHERE source_status='HAS_SOURCE')::text||'/'||count(*) FILTER(WHERE source_status='INDEPENDENT')||'/'||count(*) FILTER(WHERE source_status='SOURCE_MISSING'),count(*) FILTER(WHERE source_status='HAS_SOURCE')=170 AND count(*) FILTER(WHERE source_status='INDEPENDENT')=190 AND count(*) FILTER(WHERE source_status='SOURCE_MISSING')=40,'HAS/INDEPENDENT/MISSING' FROM tasks t JOIN a2_account a ON a.id=t.account_id;
INSERT INTO a2_checks SELECT 'task_status_matrix','250/85/65',count(*) FILTER(WHERE status='COMPLETED')::text||'/'||count(*) FILTER(WHERE status='NOT_STARTED')||'/'||count(*) FILTER(WHERE status='IN_PROGRESS'),count(*) FILTER(WHERE status='COMPLETED')=250 AND count(*) FILTER(WHERE status='NOT_STARTED')=85 AND count(*) FILTER(WHERE status='IN_PROGRESS')=65,'COMPLETED/NOT_STARTED/IN_PROGRESS' FROM tasks t JOIN a2_account a ON a.id=t.account_id;
INSERT INTO a2_checks SELECT 'task_cross_matrix','0',count(*)::text,count(*)=0,'locked source-status cross matrix' FROM (SELECT source_status,count(*) FILTER(WHERE status='COMPLETED') c,count(*) FILTER(WHERE status='NOT_STARTED') n,count(*) FILTER(WHERE status='IN_PROGRESS') p FROM tasks t JOIN a2_account a ON a.id=t.account_id GROUP BY source_status) x WHERE (source_status='HAS_SOURCE' AND (c,n,p)<>(95,40,35)) OR(source_status='INDEPENDENT' AND(c,n,p)<>(130,35,25)) OR(source_status='SOURCE_MISSING' AND(c,n,p)<>(25,10,5));
INSERT INTO a2_checks SELECT 'task_source_integrity','0',count(*)::text,count(*)=0,'same-account links and NULL source rules' FROM tasks t JOIN a2_account a ON a.id=t.account_id LEFT JOIN notes n ON n.id=t.source_note_id WHERE (t.source_status='HAS_SOURCE' AND(n.id IS NULL OR n.account_id<>t.account_id)) OR(t.source_status IN('INDEPENDENT','SOURCE_MISSING') AND t.source_note_id IS NOT NULL) OR(n.id IS NOT NULL AND n.created_at>t.created_at);
INSERT INTO a2_checks SELECT 'temp_notes_absent','0',count(*)::text,count(*)=0,'SOURCE_MISSING lifecycle temp Notes removed' FROM notes n JOIN a2_account a ON a.id=n.account_id WHERE content LIKE 'A2 temporary source lifecycle fixture %';

WITH classified AS (SELECT CASE WHEN status='COMPLETED' THEN 'COMPLETED' WHEN deadline IS NULL THEN 'NO_DEADLINE' WHEN deadline<:'reference_date'::date THEN 'OVERDUE' WHEN deadline=:'reference_date'::date THEN 'TODAY' ELSE 'UPCOMING' END bucket FROM tasks t JOIN a2_account a ON a.id=t.account_id)
INSERT INTO a2_checks SELECT 'daily_plan_matrix','250/25/8/47/70',count(*) FILTER(WHERE bucket='COMPLETED')::text||'/'||count(*) FILTER(WHERE bucket='OVERDUE')||'/'||count(*) FILTER(WHERE bucket='TODAY')||'/'||count(*) FILTER(WHERE bucket='UPCOMING')||'/'||count(*) FILTER(WHERE bucket='NO_DEADLINE'),count(*) FILTER(WHERE bucket='COMPLETED')=250 AND count(*) FILTER(WHERE bucket='OVERDUE')=25 AND count(*) FILTER(WHERE bucket='TODAY')=8 AND count(*) FILTER(WHERE bucket='UPCOMING')=47 AND count(*) FILTER(WHERE bucket='NO_DEADLINE')=70,'production precedence at reference date' FROM classified;

INSERT INTO a2_checks SELECT 'time_invariants','0',count(*)::text,count(*)=0,'publication/library/note/task created-updated ordering' FROM (SELECT 1 FROM library_videos l JOIN a2_account a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id WHERE y.published_at>l.added_at OR l.added_at>l.updated_at UNION ALL SELECT 1 FROM notes n JOIN a2_account a ON a.id=n.account_id JOIN youtube_videos y ON y.id=n.youtube_source_id WHERE y.published_at>n.created_at OR n.created_at>n.updated_at UNION ALL SELECT 1 FROM tasks t JOIN a2_account a ON a.id=t.account_id WHERE t.created_at>t.updated_at)x;

SELECT check_name,expected,actual,passed,details FROM a2_checks ORDER BY check_name;
