CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_accounts_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_accounts_display_name_not_blank CHECK (btrim(display_name) <> '')
);

CREATE UNIQUE INDEX uk_accounts_email_case_insensitive
    ON accounts (lower(email));

CREATE TABLE youtube_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    youtube_video_id VARCHAR NOT NULL,
    source_url TEXT NOT NULL,
    title TEXT,
    channel_name TEXT,
    thumbnail_url TEXT,
    duration_seconds INTEGER,
    published_at TIMESTAMPTZ,
    availability_status VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_youtube_videos_youtube_video_id UNIQUE (youtube_video_id),
    CONSTRAINT ck_youtube_videos_duration_non_negative
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0)
);

CREATE TABLE library_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    youtube_source_id BIGINT NOT NULL,
    custom_title VARCHAR(255),
    personal_description TEXT,
    added_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_library_videos_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_library_videos_youtube_source
        FOREIGN KEY (youtube_source_id) REFERENCES youtube_videos (id) ON DELETE RESTRICT,
    CONSTRAINT uk_library_videos_account_youtube_source
        UNIQUE (account_id, youtube_source_id)
);

CREATE INDEX idx_library_videos_youtube_source
    ON library_videos (youtube_source_id);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_tags_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT uk_tags_account_normalized_name UNIQUE (account_id, normalized_name),
    CONSTRAINT ck_tags_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_tags_normalized_name_not_blank CHECK (btrim(normalized_name) <> '')
);

CREATE TABLE library_video_tags (
    library_video_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT pk_library_video_tags PRIMARY KEY (library_video_id, tag_id),
    CONSTRAINT fk_library_video_tags_library_video
        FOREIGN KEY (library_video_id) REFERENCES library_videos (id) ON DELETE CASCADE,
    CONSTRAINT fk_library_video_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE INDEX idx_library_video_tags_tag
    ON library_video_tags (tag_id);

CREATE TABLE watch_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_video_id BIGINT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    last_heartbeat_at TIMESTAMPTZ NOT NULL,
    watch_time_seconds INTEGER NOT NULL,
    validity_status VARCHAR NOT NULL,
    CONSTRAINT fk_watch_sessions_library_video
        FOREIGN KEY (library_video_id) REFERENCES library_videos (id) ON DELETE CASCADE,
    CONSTRAINT ck_watch_sessions_watch_time_non_negative CHECK (watch_time_seconds >= 0)
);

CREATE INDEX idx_watch_sessions_library_validity_started
    ON watch_sessions (library_video_id, validity_status, started_at DESC);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    youtube_source_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    timestamp_seconds INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_notes_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notes_youtube_source
        FOREIGN KEY (youtube_source_id) REFERENCES youtube_videos (id) ON DELETE RESTRICT,
    CONSTRAINT ck_notes_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT ck_notes_timestamp_non_negative
        CHECK (timestamp_seconds IS NULL OR timestamp_seconds >= 0)
);

CREATE INDEX idx_notes_account_youtube_timestamp
    ON notes (account_id, youtube_source_id, timestamp_seconds);

CREATE INDEX idx_notes_account_created
    ON notes (account_id, created_at DESC);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    source_note_id BIGINT,
    source_status VARCHAR NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR NOT NULL,
    deadline DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_tasks_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tasks_source_note
        FOREIGN KEY (source_note_id) REFERENCES notes (id) ON DELETE RESTRICT,
    CONSTRAINT ck_tasks_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_tasks_status
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_tasks_source_status
        CHECK (source_status IN ('INDEPENDENT', 'HAS_SOURCE', 'SOURCE_MISSING')),
    CONSTRAINT ck_tasks_source_consistency CHECK (
        (source_status = 'INDEPENDENT' AND source_note_id IS NULL)
        OR (source_status = 'HAS_SOURCE' AND source_note_id IS NOT NULL)
        OR (source_status = 'SOURCE_MISSING' AND source_note_id IS NULL)
    )
);

CREATE INDEX idx_tasks_account_status_deadline
    ON tasks (account_id, status, deadline);

CREATE INDEX idx_tasks_source_note
    ON tasks (source_note_id);

