CREATE TABLE image_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin VARCHAR NOT NULL,
    external_url TEXT,
    storage_key VARCHAR(255),
    original_filename VARCHAR(255),
    media_type VARCHAR(100),
    size_bytes BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_image_sources_origin
        CHECK (origin IN ('EXTERNAL', 'UPLOAD')),
    CONSTRAINT ck_image_sources_shape CHECK (
        (origin = 'EXTERNAL'
            AND external_url IS NOT NULL
            AND storage_key IS NULL
            AND original_filename IS NULL
            AND media_type IS NULL
            AND size_bytes IS NULL)
        OR
        (origin = 'UPLOAD'
            AND external_url IS NULL
            AND storage_key IS NOT NULL
            AND media_type IS NOT NULL
            AND size_bytes IS NOT NULL
            AND size_bytes >= 0)
    )
);

CREATE UNIQUE INDEX uk_image_sources_external_url
    ON image_sources (external_url)
    WHERE external_url IS NOT NULL;

CREATE UNIQUE INDEX uk_image_sources_storage_key
    ON image_sources (storage_key)
    WHERE storage_key IS NOT NULL;

CREATE TABLE library_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    image_source_id BIGINT NOT NULL,
    added_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_library_images_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_library_images_source
        FOREIGN KEY (image_source_id) REFERENCES image_sources (id) ON DELETE RESTRICT,
    CONSTRAINT uk_library_images_account_source
        UNIQUE (account_id, image_source_id)
);

CREATE INDEX idx_library_images_account_added
    ON library_images (account_id, added_at DESC, id DESC);

CREATE INDEX idx_library_images_source
    ON library_images (image_source_id);

CREATE TABLE audio_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_audio_sources_url_not_blank CHECK (btrim(source_url) <> '')
);

CREATE UNIQUE INDEX uk_audio_sources_source_url
    ON audio_sources (source_url);

CREATE TABLE library_audio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    audio_source_id BIGINT NOT NULL,
    title VARCHAR(255),
    added_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_library_audio_account
        FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_library_audio_source
        FOREIGN KEY (audio_source_id) REFERENCES audio_sources (id) ON DELETE RESTRICT,
    CONSTRAINT uk_library_audio_account_source
        UNIQUE (account_id, audio_source_id)
);

CREATE INDEX idx_library_audio_account_added
    ON library_audio (account_id, added_at DESC, id DESC);

CREATE INDEX idx_library_audio_source
    ON library_audio (audio_source_id);
