[CmdletBinding()]
param([ValidatePattern('^\d{4}-\d{2}-\d{2}$')][string]$ReferenceDate='2026-08-27',[string]$EnvFile,[string]$ArtifactDirectory)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if([string]::IsNullOrWhiteSpace($EnvFile)){$EnvFile=Join-Path $PSScriptRoot '../../.env'};if([string]::IsNullOrWhiteSpace($ArtifactDirectory)){$ArtifactDirectory=Join-Path $PSScriptRoot '../a3-spec'}
. (Join-Path $PSScriptRoot 'A3-Database.ps1');$db=Get-A3DatabaseConfig $EnvFile;$ids=((Get-Content -Raw -Encoding UTF8 (Join-Path $ArtifactDirectory 'a3-source-snapshot.json')|ConvertFrom-Json).sources.youtubeVideoId -join ',')
function Get-A3Fingerprints{$lines=Invoke-A3Psql -Capture -DatabaseConfig $db -Arguments @('-q','-At','-F','|','-v',"source_ids=$ids",'-f',(Join-Path $PSScriptRoot 'fingerprint-a3.sql'));$groups=@{};foreach($scope in @('A3','A1','A2','OUTSIDE_A3','GLOBAL15')){$values=@($lines|Where-Object{$_ -like "$scope|*"}|ForEach-Object{$_.Substring($scope.Length+1)});$groups[$scope]=[pscustomobject]@{Count=$values.Count;Hash=Get-A3Sha256 $values}};return $groups}
function Invoke-A3Child([string]$Name){& powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot $Name) -ReferenceDate $ReferenceDate -EnvFile $EnvFile -ArtifactDirectory $ArtifactDirectory;if($LASTEXITCODE-ne 0){throw "$Name failed with exit code $LASTEXITCODE."}}
$before=Get-A3Fingerprints;if($before.GLOBAL15.Count-ne 15){throw "Shared global source precondition failed: expected 15 existing rows, actual $($before.GLOBAL15.Count)."};$a1Present=$before.A1.Count-gt 0;$a2Present=$before.A2.Count-gt 0
Invoke-A3Child 'Reset-Seed-A3.ps1';Invoke-A3Child 'Verify-A3.ps1';$first=Get-A3Fingerprints;Invoke-A3Child 'Reset-Seed-A3.ps1';Invoke-A3Child 'Verify-A3.ps1';$second=Get-A3Fingerprints
$fail=[Collections.Generic.List[string]]::new();if($first.A3.Hash-ne$second.A3.Hash){$fail.Add('A3 logical fingerprint changed across resets.')};foreach($scope in @('OUTSIDE_A3','GLOBAL15')){if($before[$scope].Hash-ne$first[$scope].Hash-or$first[$scope].Hash-ne$second[$scope].Hash){$fail.Add("$scope fingerprint changed.")}};if($a1Present-and($before.A1.Hash-ne$first.A1.Hash-or$first.A1.Hash-ne$second.A1.Hash)){$fail.Add('A1 fingerprint changed.')};if($a2Present-and($before.A2.Hash-ne$first.A2.Hash-or$first.A2.Hash-ne$second.A2.Hash)){$fail.Add('A2 fingerprint changed.')}
Write-Host "A3 #1: $($first.A3.Hash) ($($first.A3.Count) rows)";Write-Host "A3 #2: $($second.A3.Hash) ($($second.A3.Count) rows)";if($a1Present){Write-Host "A1 unchanged: $($second.A1.Hash) ($($second.A1.Count) rows)"}else{Write-Warning 'A1 isolation: NOT TESTED (account unavailable).'};if($a2Present){Write-Host "A2 unchanged: $($second.A2.Hash) ($($second.A2.Count) rows)"}else{Write-Warning 'A2 isolation: NOT TESTED (account unavailable).'};Write-Host "Outside A3 unchanged: $($second.OUTSIDE_A3.Hash) ($($second.OUTSIDE_A3.Count) rows)";Write-Host "Shared global 15 unchanged: $($second.GLOBAL15.Hash) ($($second.GLOBAL15.Count) rows)";if($fail.Count){$fail|ForEach-Object{Write-Error $_};exit 1};Write-Host 'A3 IDEMPOTENCE / ISOLATION: PASS'
