BEGIN TRANSACTION READ ONLY;
WITH a AS(SELECT id FROM accounts WHERE lower(email)='isolation@lifelab.local'),
checks AS(
 SELECT 'account_count' n,'1' e,count(*)::text v,count(*)=1 p,'locked identity' d FROM a
 UNION ALL SELECT 'library_count','15',count(*)::text,count(*)=15,'A3 Library' FROM library_videos l JOIN a ON a.id=l.account_id
 UNION ALL SELECT 'exact_source_set','0',count(*)::text,count(*)=0,'symmetric source difference' FROM((SELECT e.youtube_video_id FROM a3_expected_sources e EXCEPT SELECT y.youtube_video_id FROM library_videos l JOIN a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id)UNION ALL(SELECT y.youtube_video_id FROM library_videos l JOIN a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id EXCEPT SELECT e.youtube_video_id FROM a3_expected_sources e))x
 UNION ALL SELECT 'library_duplicates','0',count(*)::text,count(*)=0,'account/source uniqueness' FROM(SELECT youtube_source_id FROM library_videos l JOIN a ON a.id=l.account_id GROUP BY youtube_source_id HAVING count(*)>1)x
 UNION ALL SELECT 'shared_source_compatibility','0',count(*)::text,count(*)=0,'AVAILABLE and duration delta <=1' FROM youtube_videos y JOIN a3_expected_sources e USING(youtube_video_id) WHERE y.availability_status<>'AVAILABLE' OR abs(y.duration_seconds-e.duration)>1
 UNION ALL SELECT 'tag_count','10',count(*)::text,count(*)=10,'A3 Tags' FROM tags t JOIN a ON a.id=t.account_id
 UNION ALL SELECT 'tag_normalization','0',count(*)::text,count(*)=0,'collapsed lowercase uniqueness' FROM tags t JOIN a ON a.id=t.account_id WHERE normalized_name<>lower(regexp_replace(btrim(name),'\s+',' ','g'))
 UNION ALL SELECT 'tag_links','30',count(*)::text,count(*)=30,'A3 links' FROM library_video_tags x JOIN library_videos l ON l.id=x.library_video_id JOIN a ON a.id=l.account_id
 UNION ALL SELECT 'all_tags_used','10',count(DISTINCT x.tag_id)::text,count(DISTINCT x.tag_id)=10,'all tags used' FROM library_video_tags x JOIN tags t ON t.id=x.tag_id JOIN a ON a.id=t.account_id
 UNION ALL SELECT 'exact_tag_links','0',count(*)::text,count(*)=0,'fixture relationship difference' FROM((SELECT fixture_key,lower(tag_name) FROM a3_expected_links EXCEPT SELECT e.fixture_key,lower(t.name) FROM library_video_tags x JOIN library_videos l ON l.id=x.library_video_id JOIN a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id JOIN a3_expected_sources e USING(youtube_video_id) JOIN tags t ON t.id=x.tag_id)UNION ALL(SELECT e.fixture_key,lower(t.name) FROM library_video_tags x JOIN library_videos l ON l.id=x.library_video_id JOIN a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id JOIN a3_expected_sources e USING(youtube_video_id) JOIN tags t ON t.id=x.tag_id EXCEPT SELECT fixture_key,lower(tag_name) FROM a3_expected_links))x
 UNION ALL SELECT 'watch_total','45',count(*)::text,count(*)=45,'closed sessions' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a ON a.id=l.account_id
 UNION ALL SELECT 'watch_valid','30',count(*)::text,count(*)=30,'VALID' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a ON a.id=l.account_id WHERE validity_status='VALID'
 UNION ALL SELECT 'watch_invalid','15',count(*)::text,count(*)=15,'INVALID' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a ON a.id=l.account_id WHERE validity_status='INVALID'
 UNION ALL SELECT 'watch_other','0',count(*)::text,count(*)=0,'no other states' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a ON a.id=l.account_id WHERE validity_status NOT IN('VALID','INVALID')
 UNION ALL SELECT 'watched_unwatched','10/5',count(*)FILTER(WHERE c>0)::text||'/'||count(*)FILTER(WHERE c=0),count(*)FILTER(WHERE c>0)=10 AND count(*)FILTER(WHERE c=0)=5,'derived VALID state' FROM(SELECT l.id,count(w.id)FILTER(WHERE validity_status='VALID')c FROM library_videos l JOIN a ON a.id=l.account_id LEFT JOIN watch_sessions w ON w.library_video_id=l.id GROUP BY l.id)x
 UNION ALL SELECT 'watch_distribution','0',count(*)::text,count(*)=0,'exact per-source matrix' FROM(SELECT e.fixture_key,x.valid_count,x.invalid_count,count(w.id)FILTER(WHERE validity_status='VALID')av,count(w.id)FILTER(WHERE validity_status='INVALID')ai FROM a3_expected_sources e JOIN a3_expected_watch x USING(fixture_key) JOIN youtube_videos y USING(youtube_video_id) JOIN library_videos l ON l.youtube_source_id=y.id JOIN a ON a.id=l.account_id LEFT JOIN watch_sessions w ON w.library_video_id=l.id GROUP BY e.fixture_key,x.valid_count,x.invalid_count HAVING count(w.id)FILTER(WHERE validity_status='VALID')<>x.valid_count OR count(w.id)FILTER(WHERE validity_status='INVALID')<>x.invalid_count)x
 UNION ALL SELECT 'watch_invariants','0',count(*)::text,count(*)=0,'threshold/order/plausibility' FROM watch_sessions w JOIN library_videos l ON l.id=w.library_video_id JOIN a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id WHERE ended_at IS NULL OR started_at>last_heartbeat_at OR last_heartbeat_at>ended_at OR started_at<l.added_at OR watch_time_seconds<0 OR watch_time_seconds>y.duration_seconds OR watch_time_seconds>extract(epoch FROM(ended_at-started_at)) OR(validity_status='VALID' AND watch_time_seconds<30)OR(validity_status='INVALID' AND watch_time_seconds>=30)
 UNION ALL SELECT 'note_total','20',count(*)::text,count(*)=20,'A3 Notes' FROM notes n JOIN a ON a.id=n.account_id
 UNION ALL SELECT 'note_null_timestamps','20/0',count(*)FILTER(WHERE timestamp_seconds IS NULL)::text||'/'||count(*)FILTER(WHERE timestamp_seconds IS NOT NULL),count(*)FILTER(WHERE timestamp_seconds IS NULL)=20 AND count(*)FILTER(WHERE timestamp_seconds IS NOT NULL)=0,'NULL/non-NULL' FROM notes n JOIN a ON a.id=n.account_id
 UNION ALL SELECT 'note_distribution','0',count(*)::text,count(*)=0,'exact per-source Note counts' FROM(SELECT e.fixture_key,x.note_count,count(n.id) actual FROM a3_expected_sources e JOIN a3_expected_notes x USING(fixture_key) JOIN youtube_videos y USING(youtube_video_id) LEFT JOIN notes n ON n.youtube_source_id=y.id AND n.account_id=(SELECT id FROM a) GROUP BY e.fixture_key,x.note_count HAVING count(n.id)<>x.note_count)x
 UNION ALL SELECT 'note_source_set','0',count(*)::text,count(*)=0,'all Notes use exact current sources' FROM notes n JOIN a ON a.id=n.account_id JOIN youtube_videos y ON y.id=n.youtube_source_id LEFT JOIN a3_expected_sources e USING(youtube_video_id) WHERE e.fixture_key IS NULL
 UNION ALL SELECT 'task_total','30',count(*)::text,count(*)=30,'A3 Tasks' FROM tasks t JOIN a ON a.id=t.account_id
 UNION ALL SELECT 'task_source_matrix','12/18/0',count(*)FILTER(WHERE source_status='HAS_SOURCE')::text||'/'||count(*)FILTER(WHERE source_status='INDEPENDENT')||'/'||count(*)FILTER(WHERE source_status='SOURCE_MISSING'),count(*)FILTER(WHERE source_status='HAS_SOURCE')=12 AND count(*)FILTER(WHERE source_status='INDEPENDENT')=18 AND count(*)FILTER(WHERE source_status='SOURCE_MISSING')=0,'HAS/INDEPENDENT/MISSING' FROM tasks t JOIN a ON a.id=t.account_id
 UNION ALL SELECT 'task_status_matrix','10/10/10',count(*)FILTER(WHERE status='COMPLETED')::text||'/'||count(*)FILTER(WHERE status='NOT_STARTED')||'/'||count(*)FILTER(WHERE status='IN_PROGRESS'),count(*)FILTER(WHERE status='COMPLETED')=10 AND count(*)FILTER(WHERE status='NOT_STARTED')=10 AND count(*)FILTER(WHERE status='IN_PROGRESS')=10,'status totals' FROM tasks t JOIN a ON a.id=t.account_id
 UNION ALL SELECT 'task_cross_matrix','0',count(*)::text,count(*)=0,'exact cross matrix' FROM(SELECT source_status,count(*)FILTER(WHERE status='COMPLETED')c,count(*)FILTER(WHERE status='NOT_STARTED')n,count(*)FILTER(WHERE status='IN_PROGRESS')p FROM tasks t JOIN a ON a.id=t.account_id GROUP BY source_status)x WHERE(source_status='HAS_SOURCE' AND(c,n,p)<>(4,4,4))OR(source_status='INDEPENDENT' AND(c,n,p)<>(6,6,6))
 UNION ALL SELECT 'task_source_integrity','0',count(*)::text,count(*)=0,'same account and Note before Task' FROM tasks t JOIN a ON a.id=t.account_id LEFT JOIN notes n ON n.id=t.source_note_id WHERE(t.source_status='HAS_SOURCE' AND(n.id IS NULL OR n.account_id<>t.account_id OR n.created_at>t.created_at))OR(t.source_status='INDEPENDENT' AND t.source_note_id IS NOT NULL)OR t.source_status='SOURCE_MISSING'
 UNION ALL SELECT 'daily_plan','10/4/3/6/7',count(*)FILTER(WHERE b='COMPLETED')::text||'/'||count(*)FILTER(WHERE b='OVERDUE')||'/'||count(*)FILTER(WHERE b='TODAY')||'/'||count(*)FILTER(WHERE b='UPCOMING')||'/'||count(*)FILTER(WHERE b='NO_DEADLINE'),count(*)FILTER(WHERE b='COMPLETED')=10 AND count(*)FILTER(WHERE b='OVERDUE')=4 AND count(*)FILTER(WHERE b='TODAY')=3 AND count(*)FILTER(WHERE b='UPCOMING')=6 AND count(*)FILTER(WHERE b='NO_DEADLINE')=7,'production precedence' FROM(SELECT CASE WHEN status='COMPLETED'THEN'COMPLETED' WHEN deadline IS NULL THEN'NO_DEADLINE' WHEN deadline<:'reference_date'::date THEN'OVERDUE' WHEN deadline=:'reference_date'::date THEN'TODAY' ELSE'UPCOMING' END b FROM tasks t JOIN a ON a.id=t.account_id)x
 UNION ALL SELECT 'time_invariants','0',count(*)::text,count(*)=0,'publication/library/note/task ordering' FROM(SELECT 1 FROM library_videos l JOIN a ON a.id=l.account_id JOIN youtube_videos y ON y.id=l.youtube_source_id WHERE y.published_at>l.added_at OR l.added_at>l.updated_at UNION ALL SELECT 1 FROM notes n JOIN a ON a.id=n.account_id JOIN library_videos l ON l.youtube_source_id=n.youtube_source_id AND l.account_id=n.account_id WHERE l.added_at>n.created_at OR n.created_at>n.updated_at UNION ALL SELECT 1 FROM tasks t JOIN a ON a.id=t.account_id WHERE t.created_at>t.updated_at)x)
SELECT n,e,v,p,d FROM checks ORDER BY n;
COMMIT;
