BEGIN;SELECT pg_advisory_xact_lock(hashtext('life-lab-a3-seed'));
CREATE TEMP TABLE a3_config AS SELECT :'reference_date'::date reference_date,(:'reference_date'::date::timestamp+time '12:00') AT TIME ZONE 'Asia/Ho_Chi_Minh' reference_instant;
DO $$ BEGIN IF (SELECT count(*) FROM a3_sources)<>15 OR (SELECT count(*) FROM a3_links)<>30 OR (SELECT sum(valid_count+invalid_count) FROM a3_watch)<>45 OR (SELECT sum(note_count) FROM a3_notes)<>20 THEN RAISE EXCEPTION 'A3 artifact preflight failed';END IF;END $$;
DELETE FROM tasks WHERE account_id IN(SELECT id FROM accounts WHERE lower(email)='isolation@lifelab.local');DELETE FROM notes WHERE account_id IN(SELECT id FROM accounts WHERE lower(email)='isolation@lifelab.local');DELETE FROM tags WHERE account_id IN(SELECT id FROM accounts WHERE lower(email)='isolation@lifelab.local');DELETE FROM library_videos WHERE account_id IN(SELECT id FROM accounts WHERE lower(email)='isolation@lifelab.local');DELETE FROM accounts WHERE lower(email)='isolation@lifelab.local';
INSERT INTO youtube_videos(youtube_video_id,source_url,title,channel_name,thumbnail_url,duration_seconds,published_at,availability_status,created_at,updated_at)
SELECT s.youtube_video_id,s.source_url,s.title,s.channel_name,s.thumbnail_url,s.duration_seconds,s.published_at,s.availability_status,GREATEST(s.published_at,c.reference_instant-interval '920 days'),GREATEST(s.published_at,c.reference_instant-interval '920 days') FROM a3_sources s CROSS JOIN a3_config c ON CONFLICT(youtube_video_id) DO NOTHING;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM youtube_videos y JOIN a3_sources s USING(youtube_video_id) WHERE y.availability_status<>'AVAILABLE' OR abs(y.duration_seconds-s.duration_seconds)>1) THEN RAISE EXCEPTION 'A3 shared source compatibility failed';END IF;END $$;
INSERT INTO accounts(email,password_hash,display_name,created_at,updated_at) SELECT 'isolation@lifelab.local',:'password_hash','Isolation Demo',reference_instant-interval '180 days',reference_instant-interval '180 days' FROM a3_config;
CREATE TEMP TABLE a3_library AS WITH inserted AS(INSERT INTO library_videos(account_id,youtube_source_id,custom_title,personal_description,added_at,updated_at) SELECT a.id,y.id,NULL,CASE WHEN s.a3_order%4=0 THEN 'Isolation fixture for account-scoped behavior.' ELSE NULL END,GREATEST(y.published_at+interval '1 day',c.reference_instant-interval '150 days'+s.a3_order*interval '5 days'),GREATEST(y.published_at+interval '1 day',c.reference_instant-interval '150 days'+s.a3_order*interval '5 days') FROM a3_sources s JOIN youtube_videos y USING(youtube_video_id) CROSS JOIN accounts a CROSS JOIN a3_config c WHERE lower(a.email)='isolation@lifelab.local' RETURNING id,youtube_source_id,added_at) SELECT s.fixture_key,i.id library_video_id,i.youtube_source_id,i.added_at FROM inserted i JOIN youtube_videos y ON y.id=i.youtube_source_id JOIN a3_sources s USING(youtube_video_id);
INSERT INTO tags(account_id,name,normalized_name,created_at,updated_at) SELECT a.id,t.name,lower(regexp_replace(btrim(t.name),'\s+',' ','g')),c.reference_instant-interval '100 days'+t.ordinal*interval '1 day',c.reference_instant-interval '100 days'+t.ordinal*interval '1 day' FROM a3_tags t CROSS JOIN accounts a CROSS JOIN a3_config c WHERE lower(a.email)='isolation@lifelab.local';
INSERT INTO library_video_tags SELECT l.library_video_id,t.id FROM a3_links x JOIN a3_library l USING(fixture_key) JOIN tags t ON lower(t.name)=lower(x.tag_name) JOIN accounts a ON a.id=t.account_id WHERE lower(a.email)='isolation@lifelab.local';
WITH expanded AS(SELECT fixture_key,'VALID' validity,g no FROM a3_watch,LATERAL generate_series(1,valid_count)g UNION ALL SELECT fixture_key,'INVALID',g FROM a3_watch,LATERAL generate_series(1,invalid_count)g),p AS(SELECT e.*,l.library_video_id,l.added_at,s.a3_order,y.duration_seconds,GREATEST(l.added_at+interval '1 day',c.reference_instant-((1+(s.a3_order*11+e.no*7)%90)||' days')::interval) started,CASE WHEN e.validity='VALID' THEN LEAST(y.duration_seconds,45+((s.a3_order*13+e.no*17)%180)) ELSE 5+((s.a3_order*5+e.no*7)%25) END watched FROM expanded e JOIN a3_library l USING(fixture_key) JOIN a3_sources s USING(fixture_key) JOIN youtube_videos y ON y.id=l.youtube_source_id CROSS JOIN a3_config c)
INSERT INTO watch_sessions(library_video_id,started_at,ended_at,last_heartbeat_at,watch_time_seconds,validity_status) SELECT library_video_id,started,started+(watched+15)*interval '1 second',started+(watched+5)*interval '1 second',watched,validity FROM p;
CREATE TEMP TABLE a3_note_map AS WITH expanded AS(SELECT n.fixture_key,g note_no FROM a3_notes n,LATERAL generate_series(1,n.note_count)g),prepared AS(SELECT e.*,l.youtube_source_id,l.added_at,s.category,s.title,GREATEST(l.added_at+interval '2 days',c.reference_instant-((20+(s.a3_order*9+e.note_no*5)%80)||' days')::interval) created FROM expanded e JOIN a3_library l USING(fixture_key) JOIN a3_sources s USING(fixture_key) CROSS JOIN a3_config c),inserted AS(INSERT INTO notes(account_id,youtube_source_id,content,timestamp_seconds,created_at,updated_at) SELECT a.id,p.youtube_source_id,p.category||': review '||left(p.title,140)||CASE p.note_no WHEN 1 THEN ' and summarize the central idea.' ELSE ' and connect it to a practical example.' END,NULL,p.created,p.created FROM prepared p CROSS JOIN accounts a WHERE lower(a.email)='isolation@lifelab.local' RETURNING id,youtube_source_id,created_at) SELECT p.fixture_key,p.note_no,i.id note_id,i.created_at FROM inserted i JOIN prepared p ON p.youtube_source_id=i.youtube_source_id AND p.created=i.created_at;
CREATE TEMP TABLE a3_inserted_tasks(id bigint,status text,source_status text);
WITH desired AS(SELECT m.source_status,x.status,g no FROM a3_tasks m CROSS JOIN LATERAL(VALUES('COMPLETED',m.completed),('NOT_STARTED',m.not_started),('IN_PROGRESS',m.in_progress))x(status,n) CROSS JOIN LATERAL generate_series(1,x.n)g WHERE m.source_status='HAS_SOURCE'),numbered AS(SELECT *,row_number()OVER(ORDER BY status,no)rn FROM desired),notes AS(SELECT *,row_number()OVER(ORDER BY fixture_key,note_no)rn FROM a3_note_map),inserted AS(INSERT INTO tasks(account_id,source_note_id,source_status,title,description,status,deadline,created_at,updated_at) SELECT a.id,n.note_id,'HAS_SOURCE','Follow up on the linked learning note','Account-scoped source relationship fixture.',d.status,NULL,n.created_at+interval '1 day',n.created_at+interval '1 day' FROM numbered d JOIN notes n USING(rn) CROSS JOIN accounts a WHERE lower(a.email)='isolation@lifelab.local' RETURNING id,status,source_status) INSERT INTO a3_inserted_tasks SELECT * FROM inserted;
WITH desired AS(SELECT m.source_status,x.status,g no FROM a3_tasks m CROSS JOIN LATERAL(VALUES('COMPLETED',m.completed),('NOT_STARTED',m.not_started),('IN_PROGRESS',m.in_progress))x(status,n) CROSS JOIN LATERAL generate_series(1,x.n)g WHERE m.source_status='INDEPENDENT'),numbered AS(SELECT *,row_number()OVER(ORDER BY status,no)rn FROM desired),inserted AS(INSERT INTO tasks(account_id,source_note_id,source_status,title,description,status,deadline,created_at,updated_at) SELECT a.id,NULL,'INDEPENDENT',(ARRAY['Review Java concepts','Practice React hooks','Revisit backend architecture','Summarize database isolation','Plan focused study'])[((d.rn-1)%5)+1],'Independent A3 learning action.',d.status,NULL,c.reference_instant-((10+d.rn*3)||' days')::interval,c.reference_instant-((10+d.rn*3)||' days')::interval FROM numbered d CROSS JOIN accounts a CROSS JOIN a3_config c WHERE lower(a.email)='isolation@lifelab.local' RETURNING id,status,source_status) INSERT INTO a3_inserted_tasks SELECT * FROM inserted;
WITH incomplete AS(SELECT t.id,row_number()OVER(ORDER BY t.source_status,t.id)rn FROM tasks t JOIN accounts a ON a.id=t.account_id WHERE lower(a.email)='isolation@lifelab.local' AND t.status<>'COMPLETED') UPDATE tasks t SET deadline=CASE WHEN i.rn<=4 THEN c.reference_date-(1+i.rn)::integer WHEN i.rn<=7 THEN c.reference_date WHEN i.rn<=13 THEN c.reference_date+(i.rn-7)::integer ELSE NULL END FROM incomplete i CROSS JOIN a3_config c WHERE t.id=i.id;
COMMIT;
