[CmdletBinding()]
param([ValidatePattern('^\d{4}-\d{2}-\d{2}$')][string]$ReferenceDate='2026-08-27',[string]$EnvFile,[string]$ArtifactDirectory)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if([string]::IsNullOrWhiteSpace($EnvFile)){$EnvFile=Join-Path $PSScriptRoot '../../.env'};if([string]::IsNullOrWhiteSpace($ArtifactDirectory)){$ArtifactDirectory=Join-Path $PSScriptRoot '../a3-spec'}
. (Join-Path $PSScriptRoot 'A3-Database.ps1');& (Join-Path $PSScriptRoot 'Test-A3Artifacts.ps1') -ArtifactDirectory $ArtifactDirectory -Quiet|Out-Null
$snapshot=Get-Content -Raw -Encoding UTF8 (Join-Path $ArtifactDirectory 'a3-source-snapshot.json')|ConvertFrom-Json;$watch=Import-Csv -Delimiter "`t" -Encoding UTF8 (Join-Path $ArtifactDirectory 'a3-watch-distribution.tsv');$links=Import-Csv -Delimiter "`t" -Encoding UTF8 (Join-Path $ArtifactDirectory 'a3-tag-links-30.tsv');$notes=Import-Csv -Delimiter "`t" -Encoding UTF8 (Join-Path $ArtifactDirectory 'a3-note-distribution.tsv')
$b=[Text.StringBuilder]::new();[void]$b.AppendLine('CREATE TEMP TABLE a3_expected_sources(fixture_key text primary key,youtube_video_id text unique,duration integer);CREATE TEMP TABLE a3_expected_watch(fixture_key text primary key,valid_count integer,invalid_count integer);CREATE TEMP TABLE a3_expected_links(fixture_key text,tag_name text,primary key(fixture_key,tag_name));CREATE TEMP TABLE a3_expected_notes(fixture_key text primary key,note_count integer);')
foreach($s in $snapshot.sources){[void]$b.AppendLine("INSERT INTO a3_expected_sources VALUES ($(ConvertTo-A3SqlLiteral $s.fixtureKey),$(ConvertTo-A3SqlLiteral $s.youtubeVideoId),$([int]$s.durationSeconds));")};foreach($x in $watch){[void]$b.AppendLine("INSERT INTO a3_expected_watch VALUES ($(ConvertTo-A3SqlLiteral $x.fixture_key),$([int]$x.valid_sessions),$([int]$x.invalid_sessions));")};foreach($x in $links){[void]$b.AppendLine("INSERT INTO a3_expected_links VALUES ($(ConvertTo-A3SqlLiteral $x.fixture_key),$(ConvertTo-A3SqlLiteral $x.tag));")};foreach($x in $notes){[void]$b.AppendLine("INSERT INTO a3_expected_notes VALUES ($(ConvertTo-A3SqlLiteral $x.fixture_key),$([int]$x.note_count));")}
$tmp=Join-Path ([IO.Path]::GetTempPath()) "life-lab-a3-verify-$([guid]::NewGuid().ToString('N')).sql";[IO.File]::WriteAllText($tmp,$b.ToString()+"`n"+(Get-Content -Raw -Encoding UTF8 (Join-Path $PSScriptRoot 'verify-a3.sql')),[Text.UTF8Encoding]::new($false));$db=Get-A3DatabaseConfig $EnvFile
try{$lines=Invoke-A3Psql -Capture -DatabaseConfig $db -Arguments @('-q','-At','-F','|','-v',"reference_date=$ReferenceDate",'-f',$tmp)}finally{if(Test-Path $tmp){Remove-Item $tmp -Force}}
$results=[Collections.Generic.List[object]]::new();foreach($line in $lines){if([string]::IsNullOrWhiteSpace($line)-or $line -in @('BEGIN','COMMIT')){continue};$p=$line -split '\|',5;if($p.Count-ne 5){throw "Unexpected verifier output: $line"};$results.Add([pscustomobject]@{Check=$p[0];Expected=$p[1];Actual=$p[2];Passed=$p[3]-eq't';Details=$p[4]})};$results|Format-Table Check,Expected,Actual,Passed -AutoSize;$failed=@($results|Where-Object{-not $_.Passed});if($failed.Count){Write-Host 'A3 VERIFIER: FAIL';$failed|Format-List;exit 1};Write-Host '';Write-Host "A3 VERIFIER: PASS ($($results.Count) checks)";Write-Host "REFERENCE_DATE: $ReferenceDate"
